### ISSUE TITLE
Auth.authorize not working with angular 1.0.7

### ISSUE THREAD

**Issue by danielabar** [fnakstad/angular-client-side-auth#19]
I'm working on a project where we want to use the stable angular version 1.0.7. I tried running this project as is locally and it works. But when I downgrade the angular version in index.jade to 1.0.7 the nav bar components do not display. It seems that the directive is always returning display:none.

I debugged into Auth.authorize in services.js:
authorize: function(accessLevel, role) {

Both accessLevel and role are always undefined.

How to make it work with angular 1.0.7?

**Comment by fnakstad** [comment]
Hi Daniela, and sorry my response is so late. I just came back from a mountain trip, and haven't had an Internet connection for some days :)

I'm looking into this right now, so I'll let you know when I have a solution.

**Comment by fnakstad** [comment]
Alright, I have just pushed out a few commits which will fix this problem. I decided to go back to version 1.0.7 myself, since that's what people will be using in production anyway. The main problem was with my <code>accessLevel</code> directive... I had to put a watch on the <code>role</code> attribute I set on its tag, to make sure that it's not null when evaluating it.

Thank you so much for letting me know about this bug, and don't hesitate to post more issues if you come across any :)

**Comment by danielabar** [comment]
Thank you very much!

**Comment by hchagger** [comment]
i have the same issue. what was the fix? i am piecing together your code and i encounter this same issue.i get a value for role but undefined for accessLevel. i am using angular 1.0.7

**Comment by fnakstad** [comment]
That's strange... The fix was pushed to the repo. Do you have the latest version? Did you make any changes after cloning?
