### ISSUE TITLE
Lack of a real milestone

### ISSUE THREAD

**Issue by sdaclin** [fnakstad/angular-client-side-auth#59]
Your code is simple and very clear but it really needs a reference tag to identify your major releases.
I'm considering switching to ui-router branch and it was hard to figure what was your improvement.
By the way : thank you very much for this great work

**Comment by fnakstad** [comment]
Hi Sylvain! You are right. My approach has been a little too ad-hoc because it's pretty much a one-man project at this point. I'll make sure to rectify this in future releases with more clear milestones and versioning.

As for the UI-Router branch. I plan on merging it into master within a couple weeks or so!

**Comment by sdaclin** [comment]
I'm going to use your work on ui-router-merge branch. Thanks for this good
code.
Le 30 janv. 2014 03:57, "Frederik Nakstad" notifications@github.com a
écrit :
