### ISSUE TITLE
Initial page load should display login page

### ISSUE THREAD

**Issue by artworkad** [fnakstad/angular-client-side-auth#6]
Hi,

I went through your code (great work!) and I do not see any code that redirects to login page on page load.

You have the 

```
$rootScope.$on("$routeChangeStart", function (event, next, current)
```

but this is only relevant when route changes, right? Where is the code that checks if there is a logged in user on initial page load?

regards

**Comment by fnakstad** [comment]
Hi there, and thanks for checking out my code :)

The <code>$routeChangeStart</code> event actually also triggers on the initial page load after Angular has boostrapped the app.

Definitely check out the live deployment: http://angular-client-side-auth.herokuapp.com/
There you will notice that it will redirect you to the login page right away even though the URL I just posted in this comment points to the root. Same thing happens if you try to go straight to /admin or some other restricted route.

**Comment by artworkad** [comment]
Well in my app this is not the case. The route change is not triggered on page load and I use exactly your code. I had  to do

```
$location.path('/login');

$rootScope.$on("$routeChangeStart", function (event, next, current) {      
     $location.path('/login');        
});
```

This works. very strange. I have asked a question regarding this problem on SO http://stackoverflow.com/questions/16605199/redirect-when-app-is-initialized-in-angularjs

**Comment by fnakstad** [comment]
Hmmm, that's quite strange... Do you get the same behaviour when visiting http://angular-client-side-auth.herokuapp.com/? Do you get any error messages in the console of Chrome Developer Tools/Firebug when loading the page?

**Comment by fnakstad** [comment]
Perhaps you could make a jsFiddle where you reproduce the problem? That would make it a lot easier to debug for me :)

**Comment by artworkad** [comment]
No there are no error in console. I've setup a fiddle http://jsfiddle.net/Edsvt/ But it is not working, not sure why. However it show describe my code quite well.

**Comment by Kahramon** [comment]
Hello, 

is the problem not somewhere in app the configuration.. try with commenting the code below if you have:  
app.use(app.router);

**Comment by fnakstad** [comment]
I copied the jsFiddle code to my local machine, and played around with it a little bit. I was a little puzzled at first too, since  there were no reported errors, the run function seemed to work, and though the <code>$routeChangeStart</code> handler was successfully registered on the <code>$rootScope</code> it was never fired. However, the reason is quite simple: You do not have an <code>ngView</code> attribute in your HTML, so the <code>$route</code> service didn't know where to render your templates and thus handle route changes. Read more about <code>ngView</code> here: http://docs.angularjs.org/api/ng.directive:ngView

**Comment by JPVenson** [comment]
http://docs.angularjs.org/api/ng.directive:ngView is Offline and i the JsFiddle is also not working on my maschine and angular build (v1.5.8)
