### ISSUE TITLE
Can not run npm install on windows 7

### ISSUE THREAD

**Issue by thanhthang20** [fnakstad/angular-client-side-auth#68]
![image](https://f.cloud.github.com/assets/5382700/2365302/007da428-a6bb-11e3-8e95-6ec587c9df2c.png)

**Comment by fnakstad** [comment]
Ah, I see... This is because I have set up `bower install` as a postinstall step using the locally installed version of it, and I guess Windows is having problems with that. I've set up the postinstall script to assume a globally installed version instead. Could your try updating the repo, and see if it works for you now?

**Comment by thanhthang20** [comment]
@fnakstad Yeah, you are right. Thank you so much!.
